---
Only:
  classexists: 'SiteConfigLeftAndMain'
---
SiteConfigLeftAndMain:
  extensions:
    - SiteConfigTranslatableFix
---
Except:
  classexists: 'SiteConfigLeftAndMain'
---
CMSSettingsController:
  extensions:
    - SiteConfigTranslatableFix
